### ISSUE TITLE
手动置顶？？

### ISSUE THREAD

**Issue by dou4cc** [wind2412/wind_jvm#3]
/怒

**Comment by wind2412** [comment]
What would you want to talk? I will close it first because I really don't understand.

**Comment by dou4cc** [comment]
每次打开GitHub时间线都能看到：
 wind2412 starred wind2412/wind_jvm

**Comment by wind2412** [comment]
I think I only mis-operated it once yesterday night because I used my mobile phone, then I cancelled it at once. If it makes you feel trouble, I feel sorry but please email me instead of opening an issue.

**Comment by dou4cc** [comment]
抱歉误伤，手动置顶的是这位：https://github.com/racaljk/yvm
![](https://user-images.githubusercontent.com/7764678/38813407-6c24198c-41c1-11e8-9459-876bc85ab32c.png)

@racaljk

**Comment by wind2412** [comment]
Thank you for pointing out but in fact I dont think it's a big problem;-) Maybe he feels proud of his project very much. If u dislike it, I recommend you contact with him:-)

**Comment by y1yang0** [comment]
查看star的人手抖了。。。好吧以后点错我不restar了

**Comment by wind2412** [comment]
Yep. The star button and the stargazers botton are too closed. I've mistaken them too~
