### ISSUE TITLE
找不到主类

### ISSUE THREAD

**Issue by benyuereal** [wind2412/wind_jvm#4]
请问一下大佬 
`
/Users/apple/Documents/project/wind_jvm/bin/wind_jvm Test3
错误: 找不到或无法加载主类 Test3
`
找不到或无法加载主类 咋办

**Comment by wind2412** [comment]
在 wind_jvm 目录上 运行 ./bin/wind_jvm Test3呢

**Comment by benyuereal** [comment]
```

ben:wind_jvm Mac$ ./bin/wind_jvm Test3
wrong! --- at BootStrapClassLoader::loadClass
ben:wind_jvm Mac$ 

```
好像也是不行呀 能否加一下大佬微信

**Comment by wind2412** [comment]
奥，你是在Mac平台吧。mac上1.8+有的版本的java jar命令是有bug的。提取rt.jar之后ArrayList里边的一个内部类不会打印出来。Linux平台是可以的

**Comment by benyuereal** [comment]
那咋办 要换成jdk10版本么 还是咋办

**Comment by benyuereal** [comment]
大佬给个微信聊吧！

**Comment by wind2412** [comment]
没啥太好的解决办法，而且实际上这个项目只是用于学习的玩具而已，可能我日后不会再维护了，哈哈。我先close掉了。wind944797358

**Comment by benyuereal** [comment]
好吧
